CREATE SCHEMA LOGS;

CREATE TABLE LOGS.LOGS_INFO (INFO_OPERATION TEXT, TIME_OPERATION TIME);

CREATE
OR REPLACE PROCEDURE LOGS_INSERT (MSG TEXT) LANGUAGE PLPGSQL AS $$
BEGIN
INSERT INTO logs.logs_info VALUES (msg,localtimestamp::time);
END $$;;